# Generated by Django 6.1 on 2026-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('last_seen_location', models.CharField(blank=True, max_length=255)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('found', 'Found'), ('safe', 'Safe')], default='missing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
